import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import coffeeStoresData from "../data/coffee-stores.json"

import Banner from "../components/banner";
import Card from "../components/card";

export default function Home(props) {

  console.log(props)

  const handleOnBannerClick = () => {
    console.log("ats");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Coffee Connoisseur</h1>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerClick}/>
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400}></Image>
        </div>
        {coffeeStoresData.length > 0 &&
        <>
          <h2 className={styles.heading2}>Toronto stores</h2>
          <div className={styles.cardLayout}>
            {coffeeStoresData.map((store) => {
              return(
                <Card
                  className={styles.card}
                  key={store.id}
                  name={store.name}
                  href={`/coffee-store/${store.id}`}
                  imgUrl={store.imgUrl}
                />
              )
            })}
          </div>
        </>}
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    }
  }
}