import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import coffeeStoresData from "../data/coffee-stores.json"

import Banner from "../components/banner";
import Card from "../components/card";

export default function Home({coffeeStores}) {

  const handleOnBannerClick = () => {
    console.log("ats");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Coffee Connoisseur</h1>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerClick}/>
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400}></Image>
        </div>
        {coffeeStores.length > 0 &&
        <>
          <h2 className={styles.heading2}>{`${coffeeStores[0].location.locality} stores`}</h2>
          <div className={styles.cardLayout}>
            {coffeeStores.map((store) => {
              return(
                <Card
                  className={styles.card}
                  key={store.fsq_id}
                  name={store.name}
                  href={`/coffee-store/${store.fsq_id}`}
                  imgUrl={store.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                />
              )
            })}
          </div>
        </>}
      </main>
    </div>
  );
}

export async function getStaticProps(context) {

  const options = {
    method: 'GET',
    headers: {
      accept: 'application/json',
      Authorization: process.env.FOURSQUARE_API_KEY,
    }
  };

  const response = await fetch('https://api.foursquare.com/v3/places/search?query=coffee&ll=38.116590133305266%2C13.363525114843128&radius=5000&limit=6', options);
  const data = await response.json();

  return {
    props: {
      coffeeStores: data.results,
    }
  }
}